version: '3'

services:
  db:
    container_name: local-postgre-db
    image: postgres:latest
    ports:
      - "5432:5432"

  cache:
    container_name: local-redis-cache
    image: redis:latest
    ports:
      - "6379:6379"